### ISSUE TITLE
EC2 security group for the "30 minutes start guide"

### ISSUE THREAD

**Issue by F7502** [alien4cloud/alien4cloud.github.io#10]
There are some issues related to the creation of an EC2 security group while following the "30 minutes start guide".

1. The "30 minutes start guide" completely misses the step, that one has to create a security group named "openbar" in EC2.
2. There is no information, which ports are required to be open in this security group.
3. Creating a security group (or using an existing one) with a different name than "openbar" does not work. I changed the name of the security group in `install.pp` from "openbar" to the name of an already existing security group (with all ports open) and then run `vagrant up`. Vagrant always stopped with an error message. I discovered that the file `/opt/gigaspaces-cloudify-2.7.1-ga/clouds/ec2/ec2-cloud.groovy` on the Alien4Cloud VM still had one security group named "openbar". Even when changing that in this file, this was overwritten by someone when running `vagrant provision`.

**Comment by OresteVisari** [comment]
Hi,

Thx for your report. We actually work in a major refactoring for the 1.1.0 and we will update the 'getting started guide/30 min Start Guide!' in future.
For the moment, the 'step by step guide' of 1.1.0 and Cloudfy 3 is the best way to start with Alien4Cloud.

And yes, 'openbar' is our security group with all ports open.

Regards,
Philippe

**Comment by lucboutier** [comment]
We have fully refactored the getting started and don't use puppet/vagrant anymore.
