### ISSUE TITLE
Some links are dead - workspaces page : https://alien4cloud.github.io/#/documentation/1.3.0/user_guide/catalog_workspaces.html

### ISSUE THREAD

**Issue by billmetangmo** [alien4cloud/alien4cloud.github.io#67]
Those links are: 

https://alien4cloud.github.io/images/1.3.0/user_guide/workspace/workspace-target-upload.png
https://alien4cloud.github.io/images/1.3.0/user_guide/workspace/workspace-csar-view.png
https://alien4cloud.github.io/images/1.3.0/user_guide/workspace/request-promotion.png
https://alien4cloud.github.io/images/1.3.0/user_guide/workspace/promotion-management.png

**Comment by OresteVisari** [comment]
Thx @billmetangmo for this issue, we have re-upload the missing files in workspaces page.
