### ISSUE TITLE
The e-mail in the Get in Touch Button is not valid

### ISSUE THREAD

**Issue by gmolto** [alien4cloud/alien4cloud.github.io#69]
Hi,

The e-mail indicated in the Get in Touch button at the bottom of the front page is not valid. When sent an e-mail,  an error message is received back: "reason: 550 Denied by policy. User Unknown."

If there is an alternate contact point, please let me know.

Regards,
Germán.

**Comment by Ilanad** [comment]
@gmolto I believe the email contact (Sebastien )for Alien4Cloud is no longer working with Atos, and thus your email is bouncing.

**Comment by gmolto** [comment]
Thanks @Ilanad. Yes. I would like to know if there is another contact point to send an e-mail related to Alien4Cloud (not an Issue to be reported on GitHub).

**Comment by EdgarLGB** [comment]
@gmolto Well, I think that our [slack](https://alien4cloud-public.slack.com) will welcome you to join in.

**Comment by gmolto** [comment]
@EdgarLGB Thank you. Closing this issue.
