### ISSUE TITLE
Vagrant exits with error message due to deprecated feature

### ISSUE THREAD

**Issue by F7502** [alien4cloud/alien4cloud.github.io#9]
When running the "30 minutes start guide" Vagrant exits with an error message related to Puppet:
`Error: Could not parse application options: invalid option: --manifestdir`
The reason is that the Vagrantfile contains some deprecated features that are no more supported by the puppet version that is installed in the latest version of the used box. The solution is to use an older version of the box, which contains an older version of puppet, that still supports the deprecated feature.

This fix worked for me:
`\vm\centos-6\Vagrantfile`
After line 10, add:
`alien4cloud.vm.box_version = "1.0.1"`

In the current version of the box (> 1.0.1), a newer version of puppet is used, that leads to errors (somewhere, a deprecated feature/property is used, that has been removed in the latest puppet version...)

Hints to the solution have been found here (other projects, but same error):
https://github.com/comperiosearch/vagrant-elk-box/issues/29
https://github.com/mitchellh/vagrant/issues/6128

**Comment by lucboutier** [comment]
We have fully refactored the getting started and don't use puppet/vagrant anymore.
